// productTypes.js

export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const FILTER_BY_BRAND = "FILTER_BY_BRAND";
export const FILTER_BY_CATEGORY = "FILTER_BY_CATEGORY";
export const CATEGORIZE_PRODUCTS = "CATEGORIZE_PRODUCTS";
export const CATEGORIZE_BRANDS = "CATEGORIZE_BRANDS";
export const UPDATE_RATING_ORDER = "UPDATE_RATING_ORDER";
export const UPDATE_PRICE_ORDER = "UPDATE_PRICE_ORDER";
export const UPDATE_DISCOUNT_ORDER = "UPDATE_DISCOUNT_ORDER";
export const FILTER_PRODUCTS = "FILTER_PRODUCTS";
export const UPDATE_FILTER_PRODUCTS = "UPDATE_FILTER_PRODUCTS";
export const UPDATE_FILTER_PRODUCTS_BY_CATEGORY =
  "UPDATE_FILTER_PRODUCTS_BY_CATEGORY";
export const ADD_TO_CART = "ADD_TO_CART";
